server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
  rabbitmq:
    host: 172.16.5.50
    port: 5672
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true

